### ISSUE TITLE
Cannot zip product after using vite-ssg build

### ISSUE THREAD

**Issue by censujiang** [7th-Cyborg/vite-plugin-zip-pack#2]
example: [https://stackblitz.com/edit/github-gew6uq?file=vite.config.ts](https://stackblitz.com/edit/github-gew6uq?file=vite.config.ts)

**Comment by 7th-Cyborg** [comment]
I've checked your example and comment out zip pack entries in config and application still crashes so zip pack is not problem

**Comment by censujiang** [comment]
What is the problem?can you give me some error logs?

**Comment by 7th-Cyborg** [comment]
Sorry but i am not familiar with vuejs and vite-ssg so i cant help you with that, error is generic 'failed to load config from /home/projects/github-gew6uq-zk73nw/vite.config.ts'  probably something is wrong with config file or nodejs version might be the problem, so start there

**Comment by censujiang** [comment]
please wait,I will give you the better example

**Comment by 7th-Cyborg** [comment]
Closed since error not related to zip pack
