### ISSUE TITLE
The modification time in the zip doesn't match the local time

### ISSUE THREAD

**Issue by KilianShen** [7th-Cyborg/vite-plugin-zip-pack#4]
![image](https://github.com/7th-Cyborg/vite-plugin-zip-pack/assets/86402559/d9b9221a-a67b-4d8b-9e31-a04d8ec781b7)

*****

![image](https://github.com/7th-Cyborg/vite-plugin-zip-pack/assets/86402559/329b321f-4d6a-4fb3-aa30-8bb6a60cec00)

Maybe it's due to the time zone。

**Comment by 7th-Cyborg** [comment]
Included in release 1.0.6

**Comment by KilianShen** [comment]
I guessed it right, I learned the usage of getTimezoneOffset by looking at the 1.0.6 code.very useful plugin.
