### ISSUE TITLE
add option to ignore files

### ISSUE THREAD

**Issue by adbenitez** [7th-Cyborg/vite-plugin-zip-pack#5]
would be nice if an option is added to ignore/exclude certain file patterns from the zip, ex. to exclude `*~` backup files generated by Emacs

**Comment by reinerBa** [comment]
What about a function parameter that works like `Array.prototype.filter` ?
A function that is called for every file and if the result is true, the file will be included, otherwise excluded. The comparison of filenames could than be handelt by the developer with glob, regex or whatever.

**Comment by 7th-Cyborg** [comment]
Included in release v1.2.0
